const strings = {
	time: 'Apr 8, 2021 14:44:00',
	movie: 'Office Space',
	imageURL: 'https://raw.githubusercontent.com/MaxTechnics/CoolMovieNightThing/master/Archival/LWA.jpg',
	centerMessage: 'Movie Night starts in:',
	postCounterMessage: 'Starting soon...',
	headerText: 'Today we\'re watching: ',
	footerText: 'Presented by Retainededge and Grady\'s Physics Homework',
	RPCCountMessage: 'Starts in:',
	RPCAlmostThere: 'Starts soon!',
	RPCPostCountMsg: 'Now Playing!',
	RPClarge_image: 'frontrow',
	RPCsmall_image: 'homework',
	RPClarge_text: 'Take a seat',
	RPCsmall_text: 'This is Maxim',
	RPCbtn1TXT: 'a',
	RPCbtn1URL: 'https://www.youtube.com/watch?v=nBx37KQRbZk',
	RPCbtn2TXT: 'b',
	RPCbtn2URL: 'https://www.youtube.com/watch?v=nBx37KQRbZk',
	RPCPostCountlarge_image: 'maxim',
	RPCPostCountsmall_image: 'maxim',
	RPCPostCountlarge_text: 'Tfake a seat',
	RPCPostCountsmall_text: 'Tfhis is Maxim',
	RPCPostCountbtn1TXT: 'c',
	RPCPostCountbtn1URL: 'https://www.youtube.com/watch?v=nBx37KQRbZk',
	RPCPostCountbtn2TXT: 'd',
	RPCPostCountbtn2URL: 'https://www.youtube.com/watch?v=nBx37KQRbZk',
	version: 1
}
